// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen_dataloader

type Application struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Details   string `json:"details"`
	CreatedBy string `json:"createdBy"`
}

type NewApplication struct {
	Name      string `json:"name"`
	Details   string `json:"details"`
	CreatedBy string `json:"createdBy"`
}

type UpdateApplication struct {
	Name    string `json:"name"`
	Details string `json:"details"`
}
